import discord
from discord.ext import commands
from discord import Webhook
import aiohttp
import json
import os
from dotenv import load_dotenv
import aiofiles
import asyncio
from datetime import datetime
import requests

load_dotenv()

# Bot setup
intents = discord.Intents.all()
bot = commands.Bot(command_prefix='/', intents=intents)

# Config
WEBHOOK_URLS = {}  # Store user webhooks
DEEPSEEK_API_KEY = os.getenv('DEEPSEEK_API_KEY')
DEEPSEEK_API_URL = "https://api.deepseek.com/v1/chat/completions"

# Create scripts directory if it doesn't exist
if not os.path.exists('scripts'):
    os.makedirs('scripts')

@bot.event
async def on_ready():
    print(f'{bot.user} has connected to Discord!')
    try:
        synced = await bot.tree.sync()
        print(f"Synced {len(synced)} command(s)")
    except Exception as e:
        print(f"Error syncing commands: {e}")

# /connect command
@bot.tree.command(name="connect", description="Creates a private channel and webhook for you")
async def connect(interaction: discord.Interaction):
    await interaction.response.defer(ephemeral=True)
    
    try:
        guild = interaction.guild
        member = interaction.user
        
        # Create private channel
        overwrites = {
            guild.default_role: discord.PermissionOverwrite(view_channel=False),
            member: discord.PermissionOverwrite(view_channel=True, send_messages=True, read_messages=True)
        }
        
        channel = await guild.create_text_channel('test', overwrites=overwrites)
        
        # Create webhook
        webhook = await channel.create_webhook(name=f"{member.name}_webhook")
        
        # Store webhook info
        WEBHOOK_URLS[str(member.id)] = webhook.url
        
        # Send to DMs
        embed = discord.Embed(
            title="✅ Webhook Created!",
            description=f"Your personal webhook has been created for channel #{channel.name}",
            color=discord.Color.green()
        )
        embed.add_field(name="Webhook URL", value=f"||{webhook.url}||", inline=False)
        embed.add_field(name="Channel ID", value=channel.id, inline=True)
        embed.add_field(name="Note", value="This webhook is private to you. Don't share it!", inline=True)
        
        await interaction.followup.send(embed=embed, ephemeral=True)
        
        print(f"Created webhook for {member.name} in {channel.name}")
        
    except Exception as e:
        await interaction.followup.send(f"Error: {str(e)}", ephemeral=True)

# /source command (upload file)
@bot.tree.command(name="source", description="Upload a source file to connect with your webhook")
async def source(interaction: discord.Interaction, file: discord.Attachment):
    await interaction.response.defer(ephemeral=True)
    
    try:
        # Check if user has webhook
        if str(interaction.user.id) not in WEBHOOK_URLS:
            await interaction.followup.send("❌ You need to run `/connect` first!", ephemeral=True)
            return
        
        # Check file type
        if not file.filename.endswith(('.lua', '.txt', '.luau')):
            await interaction.followup.send("❌ Please upload a .lua or .txt file!", ephemeral=True)
            return
        
        # Save file
        filename = f"scripts/{interaction.user.id}_{file.filename}"
        await file.save(filename)
        
        # Store mapping
        WEBHOOK_URLS[f"{interaction.user.id}_source"] = filename
        
        await interaction.followup.send(f"✅ File `{file.filename}` saved and connected to your webhook!", ephemeral=True)
        
    except Exception as e:
        await interaction.followup.send(f"Error: {str(e)}", ephemeral=True)

# /makesrc command
@bot.tree.command(name="makesrc", description="Generate a Lua script with your webhook")
async def makesrc(interaction: discord.Interaction):
    await interaction.response.defer(ephemeral=True)
    
    try:
        # Check if user has source file
        source_key = f"{interaction.user.id}_source"
        if source_key not in WEBHOOK_URLS:
            await interaction.followup.send("❌ You need to upload a source file using `/source` first!", ephemeral=True)
            return
        
        webhook_url = WEBHOOK_URLS[str(interaction.user.id)]
        source_file = WEBHOOK_URLS[source_key]
        
        # Check if source file exists
        if not os.path.exists(source_file):
            await interaction.followup.send("❌ Source file not found! Please upload again with `/source`", ephemeral=True)
            return
        
        # Read original script
        async with aiofiles.open(source_file, 'r', encoding='utf-8') as f:
            original_script = await f.read()
        
        # Generate Lua script with webhook
        lua_script = f"""-- Generated by BotConnector
-- Webhook: {webhook_url}
-- Original script modified with webhook support

local webhook_url = "{webhook_url}"

function sendToWebhook(message)
    local data = {{
        content = message
    }}
    
    -- Replace with actual webhook sending method for your Lua executor
    print("Webhook ready: " .. webhook_url)
    print("Would send: " .. message)
    
    -- Uncomment for specific executors:
    -- Synapse X: syn.request({{Url = webhook_url, Method = "POST", Body = game:GetService("HttpService"):JSONEncode(data)}})
    -- Krnl: request({{Url = webhook_url, Method = "POST", Body = game:GetService("HttpService"):JSONEncode(data)}})
    -- ScriptWare: http.request(webhook_url, {{method = "POST", data = data}})
end

-- Your original script:
{original_script}

-- Usage example:
-- sendToWebhook("Hello from your script!")
"""
        
        # Save generated script
        output_file = f"scripts/{interaction.user.id}_output.lua"
        async with aiofiles.open(output_file, 'w', encoding='utf-8') as f:
            await f.write(lua_script)
        
        # Send the Lua file
        await interaction.followup.send(file=discord.File(output_file), ephemeral=True)
        
        # Cleanup after sending
        await asyncio.sleep(5)
        if os.path.exists(output_file):
            os.remove(output_file)
        
    except Exception as e:
        await interaction.followup.send(f"Error: {str(e)}", ephemeral=True)

# /ai command
@bot.tree.command(name="ai", description="Generate Lua code using AI")
async def ai(interaction: discord.Interaction, prompt: str):
    await interaction.response.defer(ephemeral=True)
    
    if not DEEPSEEK_API_KEY or DEEPSEEK_API_KEY == "your_deepseek_api_key_here":
        await interaction.followup.send("❌ AI API key not configured! Please set DEEPSEEK_API_KEY in Railway variables.", ephemeral=True)
        return
    
    try:
        headers = {
            "Authorization": f"Bearer {DEEPSEEK_API_KEY}",
            "Content-Type": "application/json"
        }
        
        data = {
            "model": "deepseek-chat",
            "messages": [
                {"role": "system", "content": "You are a Lua scripting expert for Roblox. Generate clean, efficient Lua code. Only output the code, no explanations unless asked."},
                {"role": "user", "content": f"Generate Lua code for: {prompt}"}
            ],
            "temperature": 0.7
        }
        
        async with aiohttp.ClientSession() as session:
            async with session.post(DEEPSEEK_API_URL, headers=headers, json=data) as resp:
                if resp.status == 200:
                    result = await resp.json()
                    lua_code = result['choices'][0]['message']['content']
                    
                    # Clean up code if needed
                    lua_code = lua_code.replace('```lua', '').replace('```', '').strip()
                    
                    # Save to file if long
                    if len(lua_code) > 1900:
                        filename = f"scripts/ai_output_{interaction.user.id}.lua"
                        async with aiofiles.open(filename, 'w', encoding='utf-8') as f:
                            await f.write(lua_code)
                        await interaction.followup.send(file=discord.File(filename), ephemeral=True)
                        await asyncio.sleep(5)
                        if os.path.exists(filename):
                            os.remove(filename)
                    else:
                        embed = discord.Embed(
                            title="🤖 AI Generated Lua Code",
                            description=f"**Prompt:** {prompt}\n\n```lua\n{lua_code}\n```",
                            color=discord.Color.blue()
                        )
                        await interaction.followup.send(embed=embed, ephemeral=True)
                else:
                    error_text = await resp.text()
                    await interaction.followup.send(f"❌ AI Error {resp.status}: {error_text[:200]}", ephemeral=True)
                    
    except Exception as e:
        await interaction.followup.send(f"Error: {str(e)}", ephemeral=True)

# Run bot
if __name__ == "__main__":
    token = os.getenv('DISCORD_BOT_TOKEN')
    if not token:
        print("ERROR: DISCORD_BOT_TOKEN not found in environment variables!")
        exit(1)
    bot.run(token)
